### PR TITLE
v3.0.0a1: Bump IDOM to 1.0.0 pre-release

### PR DESCRIPTION
**Pull request by Archmonger**
## Description

- Modify docs to use the upcoming IDOM-Core docs styling
   - Move docs python examples to individual files so we can run tests on them
   - CI for type checking + linting docs examples
   - Minor wording and section naming changes to feel more React-like
- Bump IDOM to 1.0.0 pre-release
   - Use the new `idom.html` API
   - Update package.json to be compatible with `idom>=1.0.0`
- Make the main `requirements.txt` be fully inclusive of all dev/user/docs dependencies to simplify development workflow
- Update `setup.py` to automatically install the latest NPM, and be easier to debug when things fail

## Checklist:

Please update this checklist as you complete each item:

-   [X] Tests have been included for all bug fixes or added functionality.
-   [X] The changelog has been updated with any significant changes, if necessary.
-   [X] GitHub Issues which may be closed by this PR have been linked.

### CODE REVIEW

**Comment by Archmonger** [comment]
@rmorshea Can you pull down this branch and check out the new docs styling with `mkdocs serve`?

**Comment by rmorshea** [comment]
`requirements.txt` is a little out of date with the current `requirements/*.txt` files. Can you update it to:
```
-r requirements/build-docs.txt
-r requirements/build-pkg.txt
-r requirements/check-style.txt
-r requirements/check-types.txt
-r requirements/dev-env.txt
-r requirements/pkg-deps.txt
-r requirements/test-env.txt
-r requirements/test-run.txt
```

**Comment by rmorshea** [comment]
Overall, I think the docs look great. I'm excited to have the core docs done in this style. The only criticism I have at the moment is that there may be some over reliance on admonitions. I don't have any alternate suggestions at the moment, but this is a thought I had when looking at this particular case:

image

**Comment by rmorshea** [comment]
I'm realizing I completely forgot to checkout this branch when I checked out the docs. The similarity to React's docs is uncanny! In some ways I prefer the mkdocs styling. I always found this part of the sidebar in the beta docs to be busy and distracting for some reason:

image

and since mkdocs doesn't have that the left sidebar is much more readable.

**Comment by Archmonger** [comment]
I considered replicating the react docs sidebar while doing this styling. But ultimately agreed with you that I think mkdocs layout is better.

Additionally if we did that, we'd be changing the mkdocs jinja templates, which is more prone to catastrophically breaking under future updates of mkdocs.

**Comment by Archmonger** [comment]
> requirements.txt is a little out of date with the current requirements/*.txt files. Can you update it to:

I left `test-run.txt` out since it seems like you already included it within `dev-env.txt`. I will re-add it for completeness.

**Review by rmorshea — APPROVED** [review]
I say we get this in so it's easier to install and test out. Since it's a pre-release it shouldn't be a huge problem if its buggy.

**Pull request merged**
