### PR TITLE
Publishing CI Workflow

### LINKED ISSUE #53: CI Workflow for PyPI/NPM Publishing
### Old Behavior

Currently no workflow exists

### New Behavior

Create a new workflow.

### Implementation Details

https://github.com/idom-team/idom/blob/main/.github/workflows/publish-js.yml
https://github.com/idom-team/idom/blob/main/.github/workflows/publish-py.yml

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/idom-team/django-idom/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by Archmonger**
- fix #53

### CODE REVIEW

**Comment by Archmonger** [comment]
I created this blind so I don't know if it works or not. Let me know.

**Comment by rmorshea** [comment]
I've got to add all the requisite secrets. Once I do that I'll give this a go.

**Comment by Archmonger** [comment]
Once v0.0.2 is published, I'll do some quick testing on it.

Afterwards, I'd like to get some visibility on `django-idom` by making some public posts.

Hopefully you'll have some time to push a release out this week.

**Comment by rmorshea** [comment]
Now that we're ready for a release, this is on my todo list.

**Review by rmorshea — APPROVED** [review]

**Pull request merged**
