### PR TITLE
Create CHANGELOG.md

### LINKED ISSUE #60: Add Changelog
We're nearly ready for a 0.0.2 release. We need a changelog though to document the work that's been done since 0.0.1.

### PR DESCRIPTION
**Pull request by Archmonger**
- fix #60

### CODE REVIEW

**Comment by Archmonger** [comment]
This changelog is ready, but I strongly suggest merging #58 before our formal release.

Some Django beginners had some issues installing IDOM, and that PR adds the detail needed to resolve that.

**Comment by Archmonger** [comment]
Did some more minor changes after re-reading. I think I'm satisfied with it now. Feel free to review.

**Comment by rmorshea** [comment]
Should there be an automated way to enforce additions to the changelog? Maybe something like [this](https://github.com/marketplace/actions/changelog-enforcer)?

**Comment by rmorshea** [comment]
That can be added later though in a different PR.

**Review by rmorshea — APPROVED** [review]

**Comment by Archmonger** [comment]
I was thinking of that too, however, it might get annoying for minor PRs such as readme spelling fixes to be forced update the changelog.

If we want to do this, we can do something about that via the `skipLabels` option within that CI workflow. Like PRs tagged with `documentation` can be skipped, and then optionally we can add a `no-changelog` tag on top of that.

But all of that might end up being more effort than manually enforcing changelog updates.

**Comment by rmorshea** [comment]
Since it'll probably just be us contributing for the time being it's probably not that important to do now.

**Pull request merged**
