### PR TITLE
bump min client requirement

### PR DESCRIPTION
**Pull request by rmorshea**
Related to breaking changes introduced by https://github.com/idom-team/idom/discussions/680

### CODE REVIEW

**Comment by rmorshea** [comment]
We should have a PR template with a checklist that includes an item about updating the changelog.

**Comment by Archmonger** [comment]
I'd say we prioritize an automated workflow over a checklist. There amount of stuff outside of core that is fully dependent on core is only going to increase over time.

**Review by Archmonger — APPROVED** [review]

**Comment by rmorshea** [comment]
Are you able to author releases?

**Comment by Archmonger** [comment]
I don't believe so. I don't see this project under my PyPI account.

**Comment by rmorshea** [comment]
You just need to be able to write a release on GitHub. I think we automated the release process.

**Comment by Archmonger** [comment]
Ah- Yes I can. Will do so now.

**Pull request merged**
